fix(log): redirect to STDERR in case of error in sourcing utils

diff --git a/app/bin/myctl b/app/bin/myctl
--- a/app/bin/myctl
+++ b/app/bin/myctl
@@ -100,7 +100,7 @@ declare -A cmd_map IMPORTED_LIBS
 
   # shellcheck source=/dev/null
 { source "$LIB_DIR"/_utils.sh && IMPORTED_LIBS[$(realpath "$LIB_DIR"/_utils.sh)]=1; } || {
-    echo "FATAL: Failed to source Utils"
+    echo "FATAL: Failed to source Utils" >&2
     exit 1
 }
 
