fix: fix installation dir detection

diff --git a/app/bin/myctl b/app/bin/myctl
--- a/app/bin/myctl
+++ b/app/bin/myctl
@@ -51,6 +51,7 @@ THIS_FILE="$(realpath "${BASH_SOURCE[0]}")"
 THIS_DIR="$(dirname "$THIS_FILE")"
 
 
+#--------- Detect MyDE installation ----------
 
 if [[ -d "$MYDE_DIR" ]] && [[ -d "$MYDE_DIR"/dots ]]; then
     INSIDE_MYDE=true
@@ -58,22 +59,33 @@ else
     INSIDE_MYDE=false
 fi
 
-# Set LIB_DIR & SRC_DIR
-for install_dir in "${INSTALL_DIRS[@]}"; do
 
-    _lib_dir="${install_dir}/lib/myctl"
-    _src_dir="${install_dir}/src/myctl"
+#--------- Set LIB_DIR & SRC_DIR -----------
 
-    if [[ -d "$_lib_dir" ]] && [[ -d "$_src_dir" ]]; then
-        LIB_DIR="$_lib_dir"
-        SRC_DIR="$_src_dir"
-        break
-    fi
-done
+_lib_dir="$THIS_DIR/../lib"
+_src_dir="$THIS_DIR/../src"
+
+if [[ -d "$_lib_dir" ]] && [[ -d "$_src_dir" ]]; then
+    LIB_DIR="$_lib_dir"
+    SRC_DIR="$_src_dir"
+else
+    for install_dir in "${INSTALL_DIRS[@]}"; do
+
+        _lib_dir="${install_dir}/lib/myctl"
+        _src_dir="${install_dir}/src/myctl"
+
+        if [[ -d "$_lib_dir" ]] && [[ -d "$_src_dir" ]]; then
+            LIB_DIR="$_lib_dir"
+            SRC_DIR="$_src_dir"
+            break
+        fi
+    done
+fi
+
 unset _lib_dir _src_dir
 
 if [[ -z "$LIB_DIR" ]] || [[ -z "$SRC_DIR" ]]; then
-    echo -e "\033[0;31mError: Couldn't find LIB_DIR or SRC_DIR.\033[0m" >&2
+    echo -e "\033[0;31mError: Couldn't find a valid myctl installation.\033[0m" >&2
     exit 1
 fi
 
@@ -88,8 +100,8 @@ declare -A cmd_map IMPORTED_LIBS
 ! [ -d "$CACHE_DIR" ] && mkdir -p "$CACHE_DIR"
 ! [ -f "$LOG_FILE" ] && touch "$LOG_FILE"
 
-  # shellcheck source=/dev/null
-{ source "$LIB_DIR"/_utils.sh && IMPORTED_LIBS[$(realpath "$LIB_DIR"/_utils.sh)]=1; } || {
+# shellcheck source=/dev/null
+{ source "$LIB_DIR"/utils.sh && IMPORTED_LIBS[$(realpath "$LIB_DIR"/utils.sh)]=1; } || {
     echo "FATAL: Failed to source Utils" >&2
     exit 1
 }
